# Generated by Django 4.0 on 2021-12-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0002_alter_bank_opening_bal_alter_expenditure_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
    ]
