# Generated by Django 4.0 on 2021-12-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_expenditure_mfs_delete_mfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
