# Generated by Django 4.0 on 2021-12-21 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_expenditure_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='app.item'),
        ),
    ]
